---
title: "It's getting hot in South East Australia"
output: html_notebook
---

```{r}
# from minYear to now
minYear <- 1981
maxYear <- 2019
```

```{r}
# may need tp install bomrang, if so then uncomment
#install.packages('bomrang')
library(bomrang)
```

```{r}
fetchHistoricRainTemperatureData <- function(latBeg, latEnd, lonBeg, lonEnd, nVals, minYear) {
  # Fetch historical climate data (max daily temperature and rain) along a transect
  # Data are from the Australian Bureau of Meteorology.
  #
  # @param latBeg start latitude
  # @param latEnd end latitude
  # @param lonBeg start longitude
  # @param lonEnd end longitude
  # @param nVals number of points along the transect
  # @return a list of list of data frames, eg. result[['rain']][[index]]
  # @note the observation point that is nearest to the selected lat, lon location is chosen
  
  res <- list()
  res$rain <- list()
  res$max_temp <- list()

  # lat/lon increments
  dLat <- (latEnd - latBeg) / (nVals - 1)
  dLon <- (lonEnd - lonBeg) / (nVals - 1)
  
  countValid <- 0
  
  # iterate over the points along the transect
  for (i in seq(0, nVals - 1)) {
    
    lat <- latBeg + i * dLat
    lon <- lonBeg + i * dLon
    location <- c(lat, lon)
    
    #
    # get the data from the observation station closest to location
    #
    
    # daily rain
    r <- get_historical(latlon=location, type='rain') %>%
                        select(-c('product_code'))
    # max daily temperature
    mt <- get_historical(latlon=location, type='max')  %>%
                         select(-c('product_code'))
    
    stationId <- toString(r$station_number[1])
    startYear <- min(r$year)

    if (startYear <= minYear) {
      # only add to the list if the starting year is <= minYear
      print(sprintf('info: pt %d, data from station %s starting at year %d will be used', i, stationId, startYear))

      res$rain[[stationId]] <- r
      res$max_temp[[stationId]] <- mt
      
      countValid <- countValid + 1
      
    } else {
      print(sprintf('Warning: pt %d, data from station %s was not selected because %d > %d', i, stationId, startYear, minYear))
    }
  }
  
  print(sprintf('info: number of retained stations: %d', countValid))
  
  return(res)
}
```

```{r}
get_monthly_stats <- function(data, yr, mo) {
  # Get monthly statistics for a given year and month
  #
  # @param data object returned by fetchHistoricRainTemperatureData. You need to retrieve the 
  #             data first!
  # @param yr year
  # @param mo month
  # @return a data.frame with total rain for the month, 
  #                      the average daily max temperature and 
  #                      the difference between the max monthly recorded temperature
  #                      and its montly average (anomaly)
  
  nVals <- length(data$rain)
  station_ids <- rep(NA, nVals)
  total_rain <- rep(NA, nVals)
  avg_max_temps <- rep(NA, nVals)
  anomaly_max_temps <- rep(NA, nVals)

  
  # rain, total during the month
  i <- 1
  for (df in data$rain) {
    rainDf <- df %>% filter(year==yr, month==mo, !is.na(rainfall))
    total_rain[i] <- sum(rainDf$rainfall)
    station_ids[i] <- df$station_number[1]
    i <- i + 1
  }
  
  # temperature, monthly average of daily max and max anomaly
  i <- 1
  for (df in data$max_temp) {
    maxTempDf <- df %>% filter(year==yr, month==mo, !is.na(max_temperature))
    avg_max_temps[i] <- mean(maxTempDf$max_temperature)
    anomaly_max_temps[i] <- max(maxTempDf$max_temperature) - avg_max_temps[i]
    i <- i + 1
  }
    
  return( data.frame(station_ids=station_ids,
                     total_rain=total_rain, 
                     anomaly_max_temp=anomaly_max_temps, 
                     avg_max_temp=avg_max_temps) )
}
```
```{r}
# Example: transect starting south of Brisbane and ending somewhere in Victoria
library(ggmap)

latBeg <- -28
latEnd <- -37

lonBeg <- 153
lonEnd <- 149.4

begEnd <- data.frame(
  lat = c(latBeg, latEnd),
  lon = c(lonBeg, lonEnd),
  stringsAsFactors = FALSE
)
oz <- c(left=112, bottom=-44, right=156, top=-10)
p1 <- get_stamenmap(oz, zoom=4, maptype='watercolor') %>% ggmap() + geom_point(data = begEnd, aes(x = lon, y = lat), color = "black", size = 2)
p1 + geom_line(data = begEnd, aes(x = lon, y = lat), color = "black", size = 0.5)
  
```
```{r}
# Beware that increasing nVals can give you an error - some stations don't have data
data <- fetchHistoricRainTemperatureData(latBeg=latBeg, latEnd=latEnd, lonBeg=lonBeg, lonEnd=lonEnd, 
                                         nVals=13, minYear=minYear - 1) # want recordings to start the previous year
```

```{r}
# Looking at the months of December, January and February
years <- seq(minYear, maxYear)
nYears <- length(years)

dec_rain <- rep(NA, nYears)
dec_avg_max_temp <- rep(NA, nYears)
dec_anomaly_max_temp <- rep(NA, nYears)

jan_rain <- rep(NA, nYears)
jan_avg_max_temp <- rep(NA, nYears)
jan_anomaly_max_temp <- rep(NA, nYears)

feb_rain <- rep(NA, nYears)
feb_avg_max_temp <- rep(NA, nYears)
feb_anomaly_max_temp <- rep(NA, nYears)

i <- 1
for (y in years) {
  
  # across stations...
  
  dec <- get_monthly_stats(data=data, yr=y, mo=12)
  dec_rain[i] <- mean(dec$total_rain)
  dec_avg_max_temp[i] <- mean(dec$avg_max_temp)
  dec_anomaly_max_temp[i] <- max(dec$anomaly_max_temp)
  
  jan <- get_monthly_stats(data=data, yr=y, mo=1)
  jan_rain[i] <- mean(jan$total_rain)
  jan_avg_max_temp[i] <- mean(jan$avg_max_temp)
  jan_anomaly_max_temp[i] <- max(jan$anomaly_max_temp)
  
  feb <- get_monthly_stats(data=data, yr=y, mo=2)
  feb_rain[i] <- mean(feb$total_rain)
  feb_avg_max_temp[i] <- mean(feb$avg_max_temp)
  feb_anomaly_max_temp[i] <- max(feb$anomaly_max_temp)

  i <- i + 1
}
df <- data.frame(year=years, 
                 dec_max_max_temp=dec_max_max_temp, 
                 jan_max_max_temp=jan_max_max_temp,
                 feb_max_max_temp=feb_max_max_temp)
```
```{r}
library(ggplot2)

ggplot(df, aes(x=year, y=dec_rain)) + geom_point() + geom_smooth(method=lm) 
ggplot(df, aes(x=year, y=jan_rain)) + geom_point() + geom_smooth(method=lm) 
ggplot(df, aes(x=year, y=feb_rain)) + geom_point() + geom_smooth(method=lm)

ggplot(df, aes(x=year, y=dec_avg_max_temp)) + geom_point() + geom_smooth(method=lm) 
ggplot(df, aes(x=year, y=jan_avg_max_temp)) + geom_point() + geom_smooth(method=lm) 
ggplot(df, aes(x=year, y=feb_avg_max_temp)) + geom_point() + geom_smooth(method=lm)

ggplot(df, aes(x=year, y=dec_anomaly_max_temp)) + geom_point() + geom_smooth(method=lm) 
ggplot(df, aes(x=year, y=jan_anomaly_max_temp)) + geom_point() + geom_smooth(method=lm) 
ggplot(df, aes(x=year, y=feb_anomaly_max_temp)) + geom_point() + geom_smooth(method=lm)


```


